### ISSUE TITLE
Website Docs

### ISSUE THREAD

**Issue by rlm8291** [Ff00ff/mammoth-website#1]
Hey 😄 

Enjoy the idea of Mammoth so far and was wondering if you have any plans regarding the website build.

I'd like to try and get more into open source development and thought these libraries would be a fun start!!

Look forward to seeing where the projects go!!

**Comment by martijndeh** [comment]
Great to hear! The website is available at https://mammoth.tools/. I haven’t shared this url yet.

So of course you can help writing the docs. I also prepared some good first issues in the Mammoth repo, see e.g. https://github.com/Ff00ff/mammoth/issues/127. This is a great one to pick up as your first issue.

I’m actually working on getting to the 1.0 release. The last thing for this is to get the cli in beta state. I also have some blog posts ready to go with this.
